HERO_SELECTION_PICKING_TIME = 20
CLASSES_EFFECTS = {
	["npc_dota_hero_ancient_apparition"] = {
		POSITIVITY = {
			EFFECT_LIST.POSITIVITY["MOVESPEED"],
			EFFECT_LIST.POSITIVITY["ATTACK_DAMAGE"],
			EFFECT_LIST.POSITIVITY["HEALTH"],
			EFFECT_LIST.POSITIVITY["ATTACK_SPEED"],
		},
		NEGATIVITY = {
			EFFECT_LIST.NEGATIVITY["LOW_MOVESPEED"],
			EFFECT_LIST.NEGATIVITY["LOW_ATTACK_DAMAGE"],
			EFFECT_LIST.NEGATIVITY["LOW_HEALTH"],
			EFFECT_LIST.NEGATIVITY["LOW_ATTACK_SPEED"],
		}
	},	
	["npc_dota_hero_antimage"] = {
		POSITIVITY = {
			EFFECT_LIST.POSITIVITY["ATTACK_DAMAGE"],
			EFFECT_LIST.POSITIVITY["HEALTH"],
			EFFECT_LIST.POSITIVITY["ATTACK_SPEED"],
		},
		NEGATIVITY = {
			EFFECT_LIST.NEGATIVITY["LOW_MOVESPEED"],
			EFFECT_LIST.NEGATIVITY["LOW_ATTACK_DAMAGE"],
			EFFECT_LIST.NEGATIVITY["LOW_HEALTH"],
		}
	},
}
