VAMPIRE_SHOP = {
	["armor"] = {
		"item_clarity",
		"item_enchanted_mango",
		"item_tango",
		"item_flask",
		"item_courier",
		"item_bottle",
		"item_ogre_axe",
		"item_staff_of_wizardry",
	},	
	["damage"] = {
		"item_staff_of_wizardry",
		"item_ring_of_protection",
		"item_orb_of_venom",
		"item_ghost",
		"item_wraith_band",
		"item_guardian_greaves",
		"item_solar_crest",
		"item_manta",
	},	
	["movespeed"] = {
		"item_staff_of_wizardry",
		"item_ring_of_protection",
		"item_orb_of_venom",
		"item_ghost",
		"item_wraith_band",
		"item_guardian_greaves",
		"item_solar_crest",
		"item_manta",
	},	
	["bottles"] = {
		"item_staff_of_wizardry",
		"item_ring_of_protection",
		"item_orb_of_venom",
		"item_ghost",
		"item_wraith_band",
		"item_guardian_greaves",
		"item_solar_crest",
		"item_manta",
	},	
	["health"] = {
		"item_staff_of_wizardry",
		"item_ring_of_protection",
		"item_orb_of_venom",
		"item_ghost",
		"item_wraith_band",
		"item_guardian_greaves",
		"item_solar_crest",
		"item_manta",
	},	
	["vampirism"] = {
		"item_staff_of_wizardry",
		"item_ring_of_protection",
		"item_orb_of_venom",
		"item_ghost",
		"item_wraith_band",
		"item_guardian_greaves",
		"item_solar_crest",
		"item_manta",
	},
}